# Generated by Django 2.2.3 on 2019-07-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190713_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
