# Generated by Django 2.2.3 on 2019-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190715_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='provider',
            field=models.CharField(blank=True, choices=[('NZ Best', 'NZ Best Tour Company'), ('NZ First', 'New Zealand First Bus Tours'), ('Little Black Bus', 'Little Black Bus Individual Tours')], max_length=30, null=True),
        ),
    ]
