# Generated by Django 2.2.3 on 2019-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='provider',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, choices=[('NZ', 'AKL'), ('NZ', 'WLG'), ('NZ', 'CHC')], max_length=30, null=True),
        ),
    ]
